updage go (#105)

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -34,11 +34,29 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
-        
+
+      - name: Start NATS service with Docker Compose
+        run: |
+          docker compose -f ${{ github.workspace }}/docker-compose.yml up -d nats
+      
+      - name: Wait for NATS service to become healthy
+        run: |
+          for i in {1..15}; do
+            if curl --fail http://localhost:8222/healthz; then
+              echo "NATS service is healthy!"
+              exit 0
+            else
+              echo "Waiting for NATS service..."
+              sleep 3
+            fi
+          done
+          echo "NATS service failed to become healthy in time."
+          exit 1
+  
       - name: Set up Go
         uses: actions/setup-go@v5
         with:
-          go-version: '1.17'
+          go-version: '1.24'
 
       - name: Run unit tests
         env:
@@ -58,6 +76,11 @@ jobs:
         with:
           name: test-logs
           path: test.log
+    
+      - name: Cleanup Docker Compose environment
+        if: always()
+        run: |
+          docker compose -f ${{ github.workspace }}/docker-compose.yml down -v
 
   build:
     runs-on: ubuntu-latest
